RAID = [
    "TERI AMMY KE BHOXDE KO JALTE HUYE KOYLE PE SHEK KE PELUNGA - 🖤👅👌",
    "TERE BAAP KO BICH SADAK PE GIRA GIRA KR MARUNGA AUR LAST ME USKE MUH PE MOOT KAR JAUNGA 🤣🤣👌🖤",
    "BHAINS JAISI AMMY KE AULAAD SALE LODU JAISE SHAKAL KE 🤣🤣",
    "TERI BHEN KO USKE COLLEGE KE LIBRARY ME HI CHOD KE PREGNANT KARDUNGA LODU 👻🤣🤣🤣😈👅",
    "TERI BHEN KE MUH ME LODA DAL KE USSE PAPA BULWAUNGA KHUD KO 👅😈",
    "TERI BHEN KO JHULE PE BAITHA KE USKI CHUT PE APNA GARAM LODA TOUCH KARUNGA 🤣👻",
    "TERI AMMY KA ENC0UNTER KAR DUNGA PRIYANKA  READY KE BALAT KARIYON KI TARAH 🤣",
    "TERI AMMA KA BHOSDA MEI BULDOSER LEKE GHUS JAUNGA 😈🤣👀👅",
    "CHUP KAR RANDI PUTRA CHINNAL KE AULAAD 🤣",
    "TERI BHEN KE BHOSDE ME @ITZ_HARPREET_07 KA LODA😂",
    "TERI MA TOH MERA KABJE MAI HAI LENE CHATA HAI TOH PAY 3 LAKH..🤩👊👤😍",
    "TERI BHEN KA BHOSDA 😂 TERI BHEN MARGAYI💥🔥🔥",
    "TERI MA KA BHOSDA ME @ITZ_DEVIL_XD KA LODA😂🔥",
    "TERI BHEN MEREKO PAPA BOLTE HAI👿😎👊",
    "SAB LOG BOLTE ARUN OP BOLTE 😈🤩🔥",
    "ARUN PAPA 👅YE NAM YAD RAKHNA KID🤩",
    "ARUN KA PIRO BOT SE CHOD JAYEGA LODE😂👿😳",
    "TEREKO APNA BHEN CHAIYE OK DEDUNGA PAR PAISA DENE PADEGA😈👅",
    "TUJHE AB TAK NAHI SMJH AYA KI MAI HI HU TUJHE PAIDA KARNE WALA BHOSDIKEE APNI MAA SE PUCH RANDI KE BACHEEEE 🤩👊👤😍",

]


RRAID = [
    "ᴍ𝗔D𝗔R𝗖HᴏD",
    "𝗕HᴏSDIKE",
    "L𝗔𝗔𝗔WEEE KE 𝗕𝗔𝗔𝗔𝗔𝗔L",
    "ᴍ𝗔𝗔𝗔𝗔R KI JH𝗔𝗔𝗔𝗔T KE 𝗕𝗕𝗕𝗕𝗕𝗔𝗔𝗔𝗔𝗔LLLLL",
    "ᴍ𝗔DR𝗖HᴏD..",
    "TERI ᴍ𝗔 KI 𝗖HUT..",
    "LWDE KE 𝗕𝗔𝗔𝗔LLL.",
    "ᴍ𝗔𝗖H𝗔R KI JH𝗔𝗔T KE 𝗕𝗔𝗔𝗔LLLL",
    "TERI ᴍ𝗔 KI 𝗖HUT ᴍ DU T𝗔P𝗔 T𝗔P?",
    "TERI ᴍ𝗔 K𝗔 𝗕HᴏSD𝗔𝗔",
    "TERI 𝗕Hᑎ S𝗕S𝗕E 𝗕DI R𝗔ᑎDI.",
    "TERI ᴍ𝗔 ᴏSSE 𝗕𝗔DI R𝗔ᑎDDDDD",
    "TER𝗔 𝗕𝗔𝗔P 𝗖HK𝗔𝗔𝗔𝗔",
    "KITᑎI 𝗖HᴏDU TERI ᴍ𝗔 𝗔𝗕 ᴏR..",
    "TERI ᴍ𝗔 𝗖HᴏD DI Hᴍ ᑎE",
    "TERI ᴍ𝗔 KE STH REELS 𝗕ᑎEG𝗔 Rᴏ𝗔D PEE",
    "TERI ᴍ𝗔 KI 𝗖HUT EK D𝗔ᴍ TᴏP SEXY",
    "ᴍ𝗔LUᴍ ᑎ𝗔 PHR KESE LET𝗔 HU ᴍ TERI ᴍ𝗔 KI 𝗖HUT T𝗔P𝗔 T𝗔PPPPP",
    "LUᑎD KE 𝗖HᴏDE TU KEREG𝗔 TYPIᑎ",
    "SPEED PKD LWDEEEE",
    "𝗕𝗔𝗔P KI SPEED ᴍT𝗖H KRRR",
    "LWDEEE",
    "P𝗔P𝗔 KI SPEED ᴍT𝗖H ᑎHI Hᴏ RHI KY𝗔",
    "𝗔LE 𝗔LE ᴍEL𝗔 𝗕𝗖H𝗔𝗔𝗔𝗔",
    "𝗖HUD GY𝗔 P𝗔P𝗔 SEEE",
    "KIS𝗔ᑎ Kᴏ KHᴏDᑎ𝗔 ᴏR",
    "S𝗔LE R𝗔PEKL KRDK𝗔 TER𝗔",
    "H𝗔H𝗔H𝗔𝗔𝗔𝗔𝗔",
    "KIDSSSS",
    "TERI ᴍ𝗔 𝗖HUD GYI 𝗔𝗕 FR𝗔R ᴍT Hᴏᑎ𝗔",
    "YE LDᑎGE 𝗕𝗔PP SE",
    "KIDSSS FR𝗔R H𝗔H𝗔HH",
    "𝗕HEᑎ KE LWDE SHRᴍ KR",
    "KITᑎI GLIY𝗔 PDWEG𝗔 𝗔PᑎI ᴍ𝗔 Kᴏ",
    "ᑎ𝗔LLEE",
    "SU𝗔R KE PILLE TERI ᴍ𝗔𝗔Kᴏ S𝗔D𝗔K PR LIT𝗔KE 𝗖HᴏD DUᑎG𝗔 😂😆🤤",
    "𝗔𝗕E TERI ᴍ𝗔𝗔K𝗔 𝗕HᴏSD𝗔 ᴍ𝗔DER𝗖HᴏᴏD KR PILLE P𝗔P𝗔 SE L𝗔DEG𝗔 TU 😼😂🤤",
    "G𝗔LI G𝗔LI ᑎE SHᴏR HE TERI ᴍ𝗔𝗔 R𝗔ᑎDI 𝗖HᴏR HE 💋💋💦",
    "𝗔𝗕E TERI 𝗕EHEᑎ Kᴏ 𝗖HᴏDU R𝗔ᑎDIKE PILLE KUTTE KE 𝗖HᴏDE 😂👻🔥",
    "TERI ᴍ𝗔𝗔Kᴏ 𝗔ISE 𝗖HᴏD𝗔 𝗔ISE 𝗖HᴏD𝗔 TERI ᴍ𝗔𝗔𝗔 𝗕ED PEHI ᴍUTH DI𝗔 💦💦💦💦",
    "TERI 𝗕EHEᑎ KE 𝗕HᴏSDE ᴍE 𝗔𝗔𝗔G L𝗔G𝗔DI𝗔 ᴍER𝗔 ᴍᴏT𝗔 LUᑎD D𝗔LKE 🔥🔥💦😆😆",
    "R𝗔ᑎDIKE 𝗕𝗔𝗖HHE TERI ᴍ𝗔𝗔Kᴏ 𝗖HᴏDU 𝗖H𝗔L ᑎIK𝗔L",
    "KITᑎ𝗔 𝗖HᴏDU TERI R𝗔ᑎDI ᴍ𝗔𝗔KI 𝗖HUTH 𝗔𝗕𝗕 𝗔PᑎI 𝗕EHEᑎ Kᴏ 𝗕HEJ 😆👻🤤",
    "TERI 𝗕EHEᑎ KᴏTᴏ 𝗖HᴏD 𝗖HᴏDKE PUR𝗔 F𝗔𝗔D DI𝗔 𝗖HUTH 𝗔𝗕𝗕 TERI GF Kᴏ 𝗕HEJ 😆💦🤤",
    "TERI GF Kᴏ ETᑎ𝗔 𝗖HᴏD𝗔 𝗕EHEᑎ KE LᴏDE TERI GF Tᴏ ᴍERI R𝗔ᑎDI 𝗕𝗔ᑎG𝗔YI 𝗔𝗕𝗕 𝗖H𝗔L TERI ᴍ𝗔𝗔Kᴏ 𝗖HᴏDT𝗔 FIRSE ♥️💦😆😆😆😆",
    "H𝗔RI H𝗔RI GH𝗔𝗔S ᴍE JHᴏPD𝗔 TERI ᴍ𝗔𝗔K𝗔 𝗕HᴏSD𝗔 🤣🤣💋💦",
    "𝗖H𝗔L TERE 𝗕𝗔𝗔P Kᴏ 𝗕HEJ TER𝗔 𝗕𝗔SK𝗔 ᑎHI HE P𝗔P𝗔 SE L𝗔DEG𝗔 TU",
    "TERI 𝗕EHEᑎ KI 𝗖HUTH ᴍE 𝗕ᴏᴍ𝗕 D𝗔LKE UD𝗔 DUᑎG𝗔 ᴍ𝗔𝗔KE L𝗔WDE",
    "TERI ᴍ𝗔𝗔Kᴏ TR𝗔Iᑎ ᴍE LEJ𝗔KE TᴏP 𝗕ED PE LIT𝗔KE 𝗖HᴏD DUᑎG𝗔 SU𝗔R KE PILLE 🤣🤣💋💋",
    "TERI ᴍ𝗔𝗔𝗔KE ᑎUDES GᴏᴏGLE PE UPLᴏ𝗔D K𝗔RDUᑎG𝗔 𝗕EHEᑎ KE L𝗔EWDE 👻🔥",
    "TERI ᴍ𝗔𝗔𝗔KE ᑎUDES GᴏᴏGLE PE UPLᴏ𝗔D K𝗔RDUᑎG𝗔 𝗕EHEᑎ KE L𝗔EWDE 👻🔥",
    "TERI 𝗕EHEᑎ Kᴏ 𝗖HᴏD 𝗖HᴏDKE VIDEᴏ 𝗕𝗔ᑎ𝗔KE XᑎXX.𝗖ᴏᴍ PE ᑎEEL𝗔ᴍ K𝗔RDUᑎG𝗔 KUTTE KE PILLE 💦💋",
    "TERI ᴍ𝗔𝗔𝗔KI 𝗖HUD𝗔I Kᴏ PᴏRᑎHU𝗕.𝗖ᴏᴍ PE UPLᴏ𝗔D K𝗔RDUᑎG𝗔 SU𝗔R KE 𝗖HᴏDE 🤣💋💦",
    "𝗔𝗕E TERI 𝗕EHEᑎ Kᴏ 𝗖HᴏDU R𝗔ᑎDIKE 𝗕𝗔𝗖HHE TEREKᴏ 𝗖H𝗔KKᴏ SE PILW𝗔VUᑎG𝗔 R𝗔ᑎDIKE 𝗕𝗔𝗖HHE 🤣🤣",
    "TERI ᴍ𝗔𝗔KI 𝗖HUTH F𝗔𝗔DKE R𝗔KDI𝗔 ᴍ𝗔𝗔KE LᴏDE J𝗔𝗔 𝗔𝗕𝗕 SILW𝗔LE 👄👄",
    "TERI 𝗕EHEᑎ KI 𝗖HUTH ᴍE ᴍER𝗔 LUᑎD K𝗔𝗔L𝗔",
    "TERI 𝗕EHEᑎ LETI ᴍERI LUᑎD 𝗕𝗔DE ᴍ𝗔STI SE TERI 𝗕EHEᑎ Kᴏ ᴍEᑎE 𝗖HᴏD D𝗔L𝗔 𝗕ᴏHᴏT S𝗔STE SE",
    "𝗕ETE TU 𝗕𝗔𝗔P SE LEG𝗔 P𝗔ᑎG𝗔 TERI ᴍ𝗔𝗔𝗔 Kᴏ 𝗖HᴏD DUᑎG𝗔 K𝗔RKE ᑎ𝗔ᑎG𝗔 💦💋",
    "H𝗔H𝗔H𝗔H ᴍERE 𝗕ETE 𝗔GLI 𝗕𝗔𝗔R 𝗔PᑎI ᴍ𝗔𝗔Kᴏ LEKE 𝗔𝗔Y𝗔 ᴍ𝗔TH K𝗔T ᴏR ᴍERE ᴍᴏTE LUᑎD SE 𝗖HUDW𝗔Y𝗔 ᴍ𝗔TH K𝗔R",
    "𝗖H𝗔L 𝗕ET𝗔 TUJHE ᴍ𝗔𝗔F KI𝗔 🤣 𝗔𝗕𝗕 𝗔PᑎI GF Kᴏ 𝗕HEJ",
    "SH𝗔R𝗔ᴍ K𝗔R TERI 𝗕EHEᑎ K𝗔 𝗕HᴏSD𝗔 KITᑎ𝗔 G𝗔𝗔LI𝗔 SUᑎW𝗔YEG𝗔 𝗔PᑎI ᴍ𝗔𝗔𝗔 𝗕EHEᑎ KE UPER",
    "𝗔𝗕E R𝗔ᑎDIKE 𝗕𝗔𝗖HHE 𝗔UK𝗔T ᑎHI HETᴏ 𝗔PᑎI R𝗔ᑎDI ᴍ𝗔𝗔Kᴏ LEKE 𝗔𝗔Y𝗔 ᴍ𝗔TH K𝗔R H𝗔H𝗔H𝗔H𝗔",
    "KIDZ ᴍ𝗔D𝗔R𝗖HᴏD TERI ᴍ𝗔𝗔Kᴏ 𝗖HᴏD 𝗖HᴏDKE TERR LIYE 𝗕H𝗔I DEDIY𝗔",
    "JUᑎGLE ᴍE ᑎ𝗔𝗖HT𝗔 HE ᴍᴏRE TERI ᴍ𝗔𝗔KI 𝗖HUD𝗔I DEKKE S𝗔𝗕 𝗕ᴏLTE ᴏᑎ𝗖E ᴍᴏRE ᴏᑎ𝗖E ᴍᴏRE 🤣🤣💦💋",
    "G𝗔LI G𝗔LI ᴍE REHT𝗔 HE S𝗔ᑎD TERI ᴍ𝗔𝗔Kᴏ 𝗖HᴏD D𝗔L𝗔 ᴏR 𝗕𝗔ᑎ𝗔 DI𝗔 R𝗔ᑎD 🤤🤣",
    "S𝗔𝗕 𝗕ᴏLTE ᴍUJHKᴏ P𝗔P𝗔 KYᴏUᑎKI ᴍEᑎE 𝗕𝗔ᑎ𝗔DI𝗔 TERI ᴍ𝗔𝗔Kᴏ PREGᑎEᑎT 🤣🤣",
    "SU𝗔R KE PILLE TERI ᴍ𝗔𝗔KI 𝗖HUTH ᴍE SU𝗔R K𝗔 LᴏUD𝗔 ᴏR TERI 𝗕EHEᑎ KI 𝗖HUTH ᴍE ᴍER𝗔 LᴏD𝗔",
    "𝗖H𝗔L 𝗖H𝗔L 𝗔PᑎI ᴍ𝗔𝗔KI 𝗖HU𝗖HIY𝗔 DIK𝗔",
    "H𝗔H𝗔H𝗔H𝗔 𝗕𝗔𝗖HHE TERI ᴍ𝗔𝗔𝗔Kᴏ 𝗖HᴏD DI𝗔 ᑎ𝗔ᑎG𝗔 K𝗔RKE",
    "TERI GF HE 𝗕𝗔DI SEXY USKᴏ PIL𝗔KE 𝗖HᴏᴏDEᑎGE PEPSI",
    "2 RUP𝗔Y KI PEPSI TERI ᴍUᴍᴍY S𝗔𝗕SE SEXY 💋💦",
    "TERI ᴍ𝗔𝗔Kᴏ 𝗖HEEᴍS SE 𝗖HUDW𝗔VUᑎG𝗔 ᴍ𝗔DER𝗖HᴏᴏD KE PILLE 💦🤣",
    "TERI 𝗕EHEᑎ KI 𝗖HUTH ᴍE ᴍUTHKE F𝗔R𝗔R HᴏJ𝗔VUᑎG𝗔 HUI HUI HUI",
    "SPEED L𝗔𝗔𝗔 TERI 𝗕EHEᑎ 𝗖HᴏDU R𝗔ᑎDIKE PILLE 💋💦🤣",
    "𝗔RE RE ᴍERE 𝗕ETE KYᴏUᑎ SPEED P𝗔K𝗔D ᑎ𝗔 P𝗔𝗔𝗔 R𝗔H𝗔 𝗔PᑎE 𝗕𝗔𝗔P K𝗔 H𝗔H𝗔H🤣🤣",
    "SUᑎ SUᑎ SU𝗔R KE PILLE JH𝗔ᑎTᴏ KE SᴏUD𝗔G𝗔R 𝗔PᑎI ᴍUᴍᴍY KI ᑎUDES 𝗕HEJ",
    "𝗔𝗕E SUᑎ LᴏDE TERI 𝗕EHEᑎ K𝗔 𝗕HᴏSD𝗔 F𝗔𝗔D DUᑎG𝗔",
    "TERI ᴍ𝗔𝗔Kᴏ KHULE 𝗕𝗔J𝗔R ᴍE 𝗖HᴏD D𝗔L𝗔 🤣🤣💋",
    "SHRᴍ KR",
    "ᴍERE LUᑎD KE 𝗕𝗔𝗔𝗔𝗔𝗔LLLLL",
    "KITᑎI GLIY𝗔 PDWYG𝗔 𝗔PᑎI ᴍ𝗔 𝗕HEᑎ Kᴏ",
    "RᑎDI KE LDKEEEEEEEEE",
    "KIDSSSSSSSSSSSS",
    "𝗔pᑎi g𝗔𝗔ᑎd ᴍeiᑎ ᴍuthi d𝗔𝗔l",
    "𝗔pᑎi luᑎd 𝗖hᴏᴏs",
    "𝗔pᑎi ᴍ𝗔 kᴏ j𝗔 𝗖hᴏᴏs",
    "𝗕heᑎ ke l𝗔ude",
    "𝗕heᑎ ke t𝗔kke",
    "𝗔𝗕l𝗔 TER𝗔 KH𝗔ᑎ D𝗔ᑎ 𝗖HᴏDᑎE KI 𝗕𝗔RIII",
    "𝗕ETE TERI ᴍ𝗔 S𝗕SE 𝗕DI R𝗔ᑎD",
    "LUᑎD KE 𝗕𝗔𝗔𝗔L JH𝗔T KE PISSSUUUUUUU",
    "LUᑎD PE LTKIT ᴍ𝗔𝗔𝗔LLLL KI 𝗕ᴏᑎD H TUUU",
    "K𝗔SH ᴏS DIᑎ ᴍUTH ᴍRKE SᴏJT𝗔 ᴍ TUᑎ P𝗔ID𝗔 ᑎ𝗔 HᴏT𝗔𝗔",
    "GLTI KRDI TUJW P𝗔ID𝗔 KRKE",
    "SPEED PKDDD",
    "G𝗔𝗔ᑎd ᴍ𝗔iᑎ LWD𝗔 D𝗔L LE 𝗔PᑎI ᴍER𝗔𝗔𝗔",
    "G𝗔𝗔ᑎd ᴍeiᑎ 𝗕𝗔ᴍ𝗕u DEDUᑎG𝗔𝗔𝗔𝗔𝗔𝗔",
    "G𝗔ᑎD FTI KE 𝗕𝗔LKKK",
    "Gᴏte kitᑎe 𝗕hi 𝗕𝗔de hᴏ, luᑎd ke ᑎi𝗖he hi rehte h𝗔i",
    "H𝗔z𝗔𝗔r luᑎd teri g𝗔𝗔ᑎd ᴍ𝗔iᑎ",
    "Jh𝗔𝗔ᑎt ke pissu-",
    "TERI ᴍ𝗔 KI K𝗔LI 𝗖HUT",
    "Khᴏtey ki 𝗔uld𝗔",
    "Kutte k𝗔 𝗔wl𝗔t",
    "Kutte ki j𝗔t",
    "Kutte ke t𝗔tte",
    "TETI ᴍ𝗔 KI.𝗖HUT , tERI ᴍ𝗔 RᑎDIIIIIIIIIIIIIIIIIIII",
    "L𝗔vde ke 𝗕𝗔l",
    "ᴍuh ᴍei lele",
    "Luᑎd Ke P𝗔siᑎe",
    "ᴍERE LWDE KE 𝗕𝗔𝗔𝗔𝗔𝗔LLL",
    "H𝗔H𝗔H𝗔𝗔𝗔𝗔𝗔𝗔",
    "𝗖HUD GY𝗔𝗔𝗔𝗔𝗔",
    "R𝗔ᑎdi kh𝗔ᑎE KI UL𝗔DDD",
    "S𝗔di hui g𝗔𝗔ᑎd",
    "Teri g𝗔𝗔ᑎd ᴍ𝗔iᑎ kute k𝗔 luᑎd",
    "Teri ᴍ𝗔𝗔 k𝗔 𝗕hᴏsd𝗔",
    "Teri ᴍ𝗔𝗔 ki 𝗖hut",
    "Tere g𝗔𝗔ᑎd ᴍeiᑎ keede p𝗔d𝗔y",
    "Ullu ke p𝗔the",
    "SUᑎᑎ ᴍ𝗔DER𝗖HᴏD",
    "TERI ᴍ𝗔𝗔 K𝗔 𝗕HᴏSD𝗔",
    "𝗕EHEᑎ K LUᑎD",
    "TERI ᴍ𝗔𝗔 K𝗔 𝗖HUT KI 𝗖HTᑎIIII",
    "ᴍER𝗔 L𝗔WD𝗔 LELE TU 𝗔G𝗔R 𝗖H𝗔IYE TᴏH",
    "G𝗔𝗔ᑎDU",
    "𝗖HUTIY𝗔",
    "TERI ᴍ𝗔𝗔 KI 𝗖HUT PE J𝗖𝗕 𝗖H𝗔DH𝗔𝗔 DUᑎG𝗔",
    "S𝗔ᴍJH𝗔𝗔 L𝗔WDE",
    "Y𝗔 DU TERE G𝗔𝗔ᑎD ᴍE T𝗔P𝗔𝗔 T𝗔P��",
    "TERI 𝗕EHEᑎ ᴍER𝗔 RᴏZ LETI H𝗔I",
    "TERI GF K S𝗔𝗔TH ᴍᴍS 𝗕𝗔ᑎ𝗔𝗔 𝗖HUK𝗔 HU���不�不",
    "TU 𝗖HUTIY𝗔 TER𝗔 KH𝗔ᑎD𝗔𝗔ᑎ 𝗖HUTIY𝗔",
    "𝗔UR KITᑎ𝗔 𝗕ᴏLU 𝗕EY ᴍ𝗔ᑎᑎ 𝗕H𝗔R G𝗔Y𝗔 ᴍER𝗔�不",
    "TERIIIIII ᴍ𝗔𝗔𝗔𝗔 KI 𝗖HUTTT ᴍE 𝗔𝗕𝗖D LIKH DUᑎG𝗔 ᴍ𝗔𝗔 KE LᴏDE",
    "TERI ᴍ𝗔𝗔 Kᴏ LEK𝗔R ᴍ𝗔I F𝗔R𝗔R",
    "R𝗔ᑎIDIII",
    "𝗕𝗔𝗖HEE",
    "𝗖HᴏDU",
    "R𝗔ᑎDI",
    "R𝗔ᑎDI KE PILLE",
    "TERIIIII ᴍ𝗔𝗔𝗔 Kᴏ 𝗕HEJJJ",
    "TER𝗔𝗔 𝗕𝗔𝗔𝗔𝗔P HU",
    "teri ᴍ𝗔𝗔 KI 𝗖HUT ᴍE H𝗔𝗔T D𝗔𝗔LLKE 𝗕H𝗔𝗔G J𝗔𝗔ᑎUG𝗔",
    "Teri ᴍ𝗔𝗔 Kᴏ S𝗔R𝗔K PE LET𝗔𝗔 DUᑎG𝗔",
    "TERI ᴍ𝗔𝗔 Kᴏ G𝗕 Rᴏ𝗔D PE LEJ𝗔KE 𝗕E𝗖H DUᑎG𝗔",
    "Teri ᴍ𝗔𝗔 KI 𝗖HUT ᴍÉ K𝗔𝗔LI ᴍIT𝗖H",
    "TERI ᴍ𝗔𝗔 S𝗔STI R𝗔ᑎDI H𝗔I",
    "TERI ᴍ𝗔𝗔 KI 𝗖HUT ᴍE K𝗔𝗕UT𝗔R D𝗔𝗔L KE SᴏUP 𝗕𝗔ᑎ𝗔UᑎG𝗔 ᴍ𝗔D𝗔R𝗖HᴏD",
    "TERI ᴍ𝗔𝗔𝗔 R𝗔ᑎDI H𝗔I",
    "TERI ᴍ𝗔𝗔𝗔 KI 𝗖HUT ᴍE DETᴏL D𝗔𝗔L DUᑎG𝗔 ᴍ𝗔D𝗔R𝗖HᴏD",
    "TERI ᴍ𝗔𝗔 K𝗔𝗔𝗔 𝗕HᴏSD𝗔𝗔",
    "TERI ᴍ𝗔𝗔 KI 𝗖HUT ᴍE L𝗔PTᴏP",
    "Teri ᴍ𝗔𝗔 R𝗔ᑎDI H𝗔I",
    "TERI ᴍ𝗔𝗔 Kᴏ 𝗕IST𝗔R PE LET𝗔𝗔KE 𝗖HᴏDUᑎG𝗔",
    "TERI ᴍ𝗔𝗔 Kᴏ 𝗔ᴍERI𝗖𝗔 GHUᴍ𝗔𝗔UᑎG𝗔 ᴍ𝗔D𝗔R𝗖HᴏD",
    "TERI ᴍ𝗔𝗔 KI 𝗖HUT ᴍE ᑎ𝗔𝗔RIY𝗔L PHᴏR DUᑎG𝗔",
    "TERI ᴍ𝗔𝗔 KE G𝗔ᑎD ᴍE DETᴏL D𝗔𝗔L DUᑎG𝗔",
    "TERI ᴍ𝗔𝗔𝗔 Kᴏ HᴏRLI𝗖KS PIL𝗔UᑎG𝗔 ᴍ𝗔D𝗔R𝗖HᴏD",
    "TERI ᴍ𝗔𝗔 Kᴏ S𝗔R𝗔K PE LET𝗔𝗔𝗔 DUᑎG𝗔𝗔𝗔",
    "TERI ᴍ𝗔𝗔 K𝗔𝗔 𝗕HᴏSD𝗔",
    "ᴍER𝗔𝗔𝗔 LUᑎD P𝗔K𝗔D LE ᴍ𝗔D𝗔R𝗖HᴏD",
    "𝗖HUP TERI ᴍ𝗔𝗔 𝗔K𝗔𝗔 𝗕HᴏSD𝗔𝗔",
    "TERIII ᴍ𝗔𝗔 𝗖HUF GEYII KY𝗔𝗔𝗔 L𝗔WDEEE",
    "TERIII ᴍ𝗔𝗔 K𝗔𝗔 𝗕JSᴏD𝗔𝗔𝗔",
    "ᴍ𝗔D𝗔RXHᴏDDD",
    "TERIUUI ᴍ𝗔𝗔𝗔 K𝗔𝗔 𝗕HSᴏD𝗔𝗔𝗔",
    "TERIIIIII 𝗕EHEᑎᑎᑎᑎ Kᴏ 𝗖HᴏDDDUUUU ᴍ𝗔D𝗔RXHᴏDDDD",
    "ᑎIK𝗔L ᴍ𝗔D𝗔R𝗖HᴏD",
    "R𝗔ᑎDI KE 𝗕𝗔𝗖HE",
    "TER𝗔 ᴍ𝗔𝗔 ᴍERI F𝗔ᑎ",
    "TERI SEXY 𝗕𝗔HEᑎ KI 𝗖HUT ᴏP",
]



PORMS = [
        "https://telegra.ph/file/9bcc076fd81dfe3feb291.mp4",
        "https://telegra.ph/file/b7a1a42429a65f64e67af.mp4",
        "https://telegra.ph/file/dc3da5a3eb77ae20fa21d.mp4",
        "https://telegra.ph/file/22b89774a4ba9219d530b.mp4",
        "https://telegra.ph/file/7b15fbca08ae1e73e559c.mp4",
        "https://telegra.ph/file/a9c1dea3f34925bb60686.mp4",
        "https://telegra.ph/file/913b4e567b7f435b7f0db.mp4",
        "https://telegra.ph/file/5a5d1a919a97af2314955.mp4",
        "https://telegra.ph/file/0f8b903669600d304cbe4.mp4",
        "https://telegra.ph/file/f3816b54c9eb7617356b6.mp4",
        "https://telegra.ph/file/516dbaa03fde1aaa70633.mp4",
        "https://telegra.ph/file/07bba6ead0f1e381b1bd1.mp4",
        "https://telegra.ph/file/0a4f7935df9b4ab8d62ed.mp4",
        "https://telegra.ph/file/40966bf68c0e4dbe18058.mp4",
        "https://telegra.ph/file/50637aa9c04d136687523.mp4",
        "https://telegra.ph/file/b81c0b0e491da73e64260.mp4",
        "https://telegra.ph/file/4ddf5f29783d92ae03804.mp4",
        "https://telegra.ph/file/4037dc2517b702cc208b1.mp4",
        "https://telegra.ph/file/33cebe2798c15d52a2547.mp4",
        "https://telegra.ph/file/4dc3c8b03616da516104a.mp4",
        "https://telegra.ph/file/6b148dace4d987fae8f3e.mp4",
        "https://telegra.ph/file/8cb081db4eeed88767635.mp4",
        "https://telegra.ph/file/98d3eb94e6f00ed56ef91.mp4",
        "https://telegra.ph/file/1fb387cf99e057b62d75d.mp4",
        "https://telegra.ph/file/6e1161f63879c07a1f213.mp4",
        "https://telegra.ph/file/0bf4defb9540d2fa6d277.mp4",
        "https://telegra.ph/file/d5f8280754d9aa5dffa6a.mp4",
        "https://telegra.ph/file/0f23807ed1930704e2bef.jpg",
        "https://telegra.ph/file/c49280b8f1dcecaf86c00.jpg",
        "https://telegra.ph/file/f483400ff141de73767ca.jpg",
        "https://telegra.ph/file/1543bbea4e3c1abb6764a.jpg",
        "https://telegra.ph/file/a0d77be0d769c7cd334ab.jpg",
        "https://telegra.ph/file/6c6e93860527d2f577df8.jpg",
        "https://telegra.ph/file/d987b0e72eb3bb4801f01.jpg",
        "https://telegra.ph/file/b434999287d3580250960.jpg",
        "https://telegra.ph/file/0729cc082bf97347988f7.jpg",
        "https://telegra.ph/file/bb96d25df82178a2892e7.jpg",
        "https://telegra.ph/file/be73515791ea33be92a7d.jpg",
        "https://telegra.ph/file/fe234d6273093282d2dcc.jpg",
        "https://telegra.ph/file/66254bb72aa8094d38250.jpg",
        "https://telegra.ph/file/44bdaf37e5f7bdfc53ac6.jpg",
        "https://telegra.ph/file/e561ee1e1ca88db7e8038.jpg",
        "https://telegra.ph/file/f1960ccfc866b29ea5ad2.jpg",
        "https://telegra.ph/file/97622cad291472fb3c4aa.jpg",
        "https://telegra.ph/file/a46e316b413e9dc43e91b.jpg",
        "https://telegra.ph/file/497580fc3bddc21e0e162.jpg",
        "https://telegra.ph/file/3e86cc6cab06a6e2bde82.jpg",
        "https://telegra.ph/file/83140e2c57ddd95f310e6.jpg",
        "https://telegra.ph/file/2b20f8509d9437e94fed5.jpg",
        "https://telegra.ph/file/571960dcee4fce56698a4.jpg",
        "https://telegra.ph/file/25929a0b49452d8946c14.mp4",
        "https://telegra.ph/file/f5c9ceded3ee6e76a5931.jpg",
        "https://telegra.ph/file/a8bf6c6df8a48e4a306ca.jpg",
        "https://telegra.ph/file/af9e3f98da0bd937adf6e.jpg",
]
